# Generated by Django 6.0.4 on 2026-05-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_ai_metadata_suggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
