# Generated by Django 6.0.4 on 2026-05-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ai_metadata_provider',
            field=models.CharField(blank=True, choices=[('ollama', 'Ollama'), ('gemini', 'Gemini'), ('bedrock', 'AWS Bedrock Nova Lite')], max_length=20),
        ),
    ]
