# Generated by Codex on 2026-05-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_documentchunk"),
    ]

    operations = []
