# Generated by Codex on 2026-05-28

from django.db import migrations
import pgvector.django


def backfill_embedding_vectors(apps, schema_editor):
    DocumentChunk = apps.get_model("documents", "DocumentChunk")

    for chunk in DocumentChunk.objects.exclude(embedding=[]).iterator():
        embedding = chunk.embedding

        if isinstance(embedding, list) and len(embedding) == 1024:
            chunk.embedding_vector = embedding
            chunk.save(update_fields=["embedding_vector"])


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_documentchunk"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="embedding_vector",
            field=pgvector.django.VectorField(
                blank=True,
                dimensions=1024,
                null=True,
            ),
        ),
        migrations.RunPython(
            backfill_embedding_vectors,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX IF NOT EXISTS "
                "documents_documentchunk_embedding_vector_hnsw "
                "ON documents_documentchunk "
                "USING hnsw (embedding_vector vector_cosine_ops) "
                "WHERE embedding_vector IS NOT NULL"
            ),
            reverse_sql=(
                "DROP INDEX IF EXISTS "
                "documents_documentchunk_embedding_vector_hnsw"
            ),
        ),
    ]
