apiVersion: v1
kind: ConfigMap
metadata:
  name: docmanager-config
data:
  DJANGO_DEBUG: "False"
  DJANGO_SECURE_SSL_REDIRECT: "False"
  DB_ENGINE: "postgresql"
  DB_HOST: "postgresql"
  DB_PORT: "5432"
  MAX_UPLOAD_SIZE_MB: "20"
  DOCUMENTS_PER_PAGE: "10"
  AI_METADATA_PROVIDER: "bedrock"
  OLLAMA_BASE_URL: "http://ollama:11434"
  OLLAMA_MODEL: "qwen2.5:0.5b"
  OLLAMA_TIMEOUT_SECONDS: "90"
  OLLAMA_NUM_CTX: "1024"
  GEMINI_BASE_URL: "https://generativelanguage.googleapis.com"
  GEMINI_MODEL: "gemini-2.5-flash"
  AWS_REGION: "us-east-1"
  BEDROCK_NOVA_MODEL_ID: "amazon.nova-lite-v1:0"
  BEDROCK_EMBED_MODEL_ID: "amazon.titan-embed-text-v2:0"
  BEDROCK_TIMEOUT_SECONDS: "90"
  AI_METADATA_MAX_CHARS: "2500"
  AI_EMBEDDING_MAX_CHARS: "2500"
  AI_EMBEDDING_DIMENSIONS: "1024"
  AI_SEARCH_TOP_K: "5"
  AI_RAG_TOP_K: "5"
  AI_RAG_MAX_CONTEXT_CHARS: "1800"
  AI_RAG_MAX_ANSWER_TOKENS: "700"
  OPENSEARCH_URL: "http://opensearch:9200"
  OPENSEARCH_INDEX_PREFIX: "docmanager"
  OPENSEARCH_DOCUMENT_INDEX: "docmanager-documents"
  OPENSEARCH_CHUNK_INDEX: "docmanager-document-chunks"
  OPENSEARCH_TIMEOUT_SECONDS: "10"
  AUTO_AI_METADATA_ON_UPLOAD: "True"
  ALLOWED_HOSTS: "document-app-document-app.apps-crc.testing,localhost,127.0.0.1,docsdemo.khalique.net"
  MEDIA_ROOT: "/app/media"
  OKTA_DOMAIN: "https://integrator-8551728.okta.com"
  OKTA_ISSUER: "https://integrator-8551728.okta.com/oauth2/default"
  OKTA_CALLBACK_URL: "https://docsdemo.khalique.net/oidc/callback"
  OKTA_LOGOUT_REDIRECT_URL: "https://docsdemo.khalique.net/"
  CLOUD_FLARE_ZONEID: "603726fa14e645b7f19164ce6842e597"
  CLOUD_FLARE_REC: "aws.khalique.us"
  CLOUD_FLARE_TARGET: "f87be553c48944dc84d0a3a966d0c3281d.mylabserver.com"
