apiVersion: batch/v1
kind: Job
metadata:
  name: docmanager-migrate
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: docker.io/khalique/document-app:2.6-metadata-quality-batch
          command:
            - python
            - manage.py
            - migrate
            - --noinput
          envFrom:
            - configMapRef:
                name: docmanager-config
            - secretRef:
                name: docmanager-secrets
          volumeMounts:
            - name: media
              mountPath: /app/media
      restartPolicy: OnFailure
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: docmanager-media-pvc
