apiVersion: v1
kind: ConfigMap
metadata:
  name: docmanager-config
data:
  DJANGO_DEBUG: "False"
  DJANGO_SECURE_SSL_REDIRECT: "False"
  MAX_UPLOAD_SIZE_MB: "20"
  DOCUMENTS_PER_PAGE: "10"
  AI_METADATA_PROVIDER: "ollama"
  OLLAMA_BASE_URL: "http://ollama:11434"
  OLLAMA_MODEL: "qwen2.5:0.5b"
  OLLAMA_TIMEOUT_SECONDS: "90"
  OLLAMA_NUM_CTX: "1024"
  GEMINI_BASE_URL: "https://generativelanguage.googleapis.com"
  GEMINI_MODEL: "gemini-2.5-flash"
  AI_METADATA_MAX_CHARS: "2500"
  AUTO_AI_METADATA_ON_UPLOAD: "True"
  ALLOWED_HOSTS: "document-app-document-app.apps-crc.testing,localhost,127.0.0.1,docsdemo.khalique.net"
  MEDIA_ROOT: "/app/media"
  OKTA_DOMAIN: "https://trial-9422381.okta.com"
  OKTA_ISSUER: "https://trial-9422381.okta.com/oauth2/default"
  OKTA_CALLBACK_URL: "https://docsdemo.khalique.net/oidc/callback"
  OKTA_LOGOUT_REDIRECT_URL: "https://docsdemo.khalique.net/"
