apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aws-khalique-us-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  # This tells Nginx to accept requests meant for your custom domain
  - host: aws.khalique.us
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: document-app
            port:
              number: 80